version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-frontend
    ports:
      - "3001:3001"  # Next.js production
      - "4000:4000"  # Express server.js
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhostd:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
      - NEXTAUTH_URL=http://localhost:3001
      - NEXT_PUBLIC_SERVER_NODE_API=http://localhost:4000
      - NEXT_PUBLIC_MLOPS_BACKEND_API_URL=http://localhost:8686
      - NEXTAUTH_SECRET=Zf3k2oXx9P0rBp1p9Hq3A8MkxA2v7HtM
      - NEXTAUTH_JWT_SECRET=Q5jvhvJ8Np0aD9xDt59d5h2Jv14lKQOp
      
    volumes:
      - ./.env.local:/app/.env.local
    # depends_on:
    #   - backend  # Nếu frontend phụ thuộc vào backend, uncomment dòng này.
    networks:
      - mlops-net

networks:
  mlops-net:
    driver: bridge
