flow_module: flows.train_flow
data_type: timeseries  # Specify 'image' or 'timeseries'
model:
    image:
        model_name: image_classification
        input_size:
            w: 224
            h: 224
        classes:
            - butterfly
            - cat
            - chicken
            - cow
            - dog
            - elephant
            - horse
            - sheep
            - spider
            - squirrel
        model_type: ResNet50
        version: ver001
        classifier_activation: softmax
        classifier_type: multi-class
        classification_layer: classify_head
        save_dir: /home/ariya/workspace/models/image/{model_name}
        drift_detection:
            uae_model_suffix: _uae
            uae_encoding_dims: 128
            bbsd_model_suffix: _bbsd
            bbsd_layer_idx: -1
            reference_data_suffix: _ref_data
            reference_data_n_sample: 1000

    timeseries:
        model_name: stock_prediction
        version: ver001
        model_type: BiLSTM # Options: LSTM, GRU, BiLSTM, Conv1D-BiLSTM
        time_step: 30
        input_size:
            h: 30
            w: 1
        framework: tensorflow
        save_dir: /home/ariya/workspace/models/timeseries/{model_name}

        data:
            input_format:
                - "30-step sequences with 1 feature per step"
            normalization: "min-max scaling"

        metadata:
            description: "Time-series prediction model"
            created_by: "ariya"
            created_date: "2025-01-23"


dataset:
    ds_root: /home/ariya/workspace/datasets/
    ds_name: Stock_product_01  # For Timeseries datasets
    dvc_tag: v2.0.0
    dvc_checkout: true
    file_path: /home/ariya/workspace/datasets/timeseries/37510-P0100_재고량.csv   # File path for time-series data
    date_col: TransactionDate  # Column containing date information
    target_col: Stock  # Target column
    time_step: 30  # Specify the number of time steps
    dvc_data_dir: /home/ariya/workspace/datasets/Stock_product_01

train:
    hparams:
        epochs: 5
        # batch_size: 64
        # init_lr: 0.001
        # lstm_units: 128  # For time-series models
        # conv_filters: 128  # For Conv1D-BiLSTM models
        # kernel_size: 3
        # dropout_rate: 0.2
    mlflow:
        exp_name: Time Series Model Training
        exp_desc: Train a model for stock prediction on time-series data
        exp_tags:
            dataset: Mixed

