flow_module: flows.full_flow

pipeline: 
    data_flow: 0
    train_flow: 0
    eval_flow: 0
    deploy_flow: 0

data_type: timeseries  # Specify 'image' or 'timeseries'

dataset:
    ds_name: Stock_product_03 # For Timeseries datasets
    dvc_tag: ['제조', '센서', '실시간']
    dvc_checkout: true
    file_path: /home/ariya/workspace/datasets/timeseries/62441-AR000_재고량.xlsx   # File path for time-series data
    date_col: TransactionDate  # Column containing date information
    target_col: Stock  # Target column
    time_step: 30  # Specify the number of time steps
    ds_author: 박진제
    ds_description: Stock amount of product ....


model:
    image:
        model_name: image_classification
        input_size:
            w: 224
            h: 224
        classes:
            - butterfly
            - cat
            - chicken
            - cow
            - dog
            - elephant
            - horse
            - sheep
            - spider
            - squirrel
        model_type: ResNet50
        model_version: 0
        framework: PyTorch
        classifier_activation: softmax
        classifier_type: multi-class
        classification_layer: classify_head
        drift_detection:
            uae_model_suffix: _uae
            uae_encoding_dims: 128
            bbsd_model_suffix: _bbsd
            bbsd_layer_idx: -1
            reference_data_suffix: _ref_data
            reference_data_n_sample: 1000

    timeseries:
        model_name: stock_prediction
        model_version: 2
        model_type: Conv1D-BiLSTM # Options: LSTM, GRU, BiLSTM, Conv1D-BiLSTM
        time_step: 30
        input_size:
            h: 30
            w: 1
        framework: Tensorflow

        data:
            input_format:
                - "30-step sequences with 1 feature per step"
            normalization: "min-max scaling"

        metadata:
            description: "Time-series prediction model"
            created_by: "4INLAB"
            created_date: "2025-01-23"


train:
    image:
        hparams:
            epochs: 10
            batchSize: 64
            learningRate: 0.001
            lstm_units: 128  # For time-series models
            conv_filters: 128  # For Conv1D-BiLSTM models
            kernel_size: 3
            dropout_rate: 0.2
        mlflow:
            exp_name: Image Classification Training
            exp_desc: Train a model for Image Classification 
            exp_tags:
                dataset: Mixed
    timeseries:
        hparams:
            epochs: 10
            batchSize: 64
            learningRate: 0.001
            lstm_units: 128  # For time-series models
            conv_filters: 128  # For Conv1D-BiLSTM models
            kernel_size: 3
            dropout_rate: 0.2
        mlflow:
            exp_name: Timeseries Stock Prediction Training
            exp_desc: Train a model for stock prediction on time-series data
            exp_tags:
                dataset: Mixed
            
evaluate:
    image:  # Configuration specific to image data
        subset: test
        mlflow:
            exp_name: Evaluate Animals10 Classifier
            exp_desc: Evaluate an image classification model
            exp_tags:
                dataset: Animals10
    timeseries:  # Configuration specific to time-series data
        subset: test
        mlflow:
            exp_name: Timeseries Stock Prediction Evaluation
            exp_desc: Evaluate a time-series model for stock prediction
            exp_tags:
                dataset: Time Series Data

            
deploy:
    # prefect:
    #     git_repo_root: ~/workspace/deployments/prefect-deployments
    #     name: all_flow_deployment
    #     version: null
    #     tags: []
    #     description: "Evaluate a time-series model every day."
    #     schedule:
    #     rrule: 'FREQ=DAILY;INTERVAL=1'  # Run every day
    #     entrypoint: "flows.eval_flow.eval_flow"  # Path to the eval flow function
    #     parameters:
    #     model_metadata_file_path: "/home/ariya/central_storage/models/timeseries/stock_prediction_BiLSTM_ver008/stock_prediction.yaml"
    #     run_name: "stock_prediction_BiLSTM_ver008"
    #     dvc_data_dir: "/home/ariya/workspace/datasets/Stock_product_01"
    #     work_pool:
    #     name: "default-agent-pool"